/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import ControlClasses.Category;
import ControlClasses.sound;
import Gui.AdminPanels.Blank;
import Gui.AdminPanels.AddEmp;
import Gui.AdminPanels.CategoryPanel;
import Gui.AdminPanels.ListEmps;
import Gui.AdminPanels.ModifyEmp;
import Gui.AdminPanels.Style;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author omar waheed
 */
public class AdminFrame extends javax.swing.JFrame {
    LogIn L;
    AddEmp p1;
    Blank  p2;
    ListEmps p3;
    ModifyEmp p4;
    CategoryPanel p5;
    Style  p6;
    CardLayout layout;
    sound s;
    public AdminFrame() {
        
        initComponents();
        layout=new CardLayout();
        p1=new AddEmp();
        p2=new Blank();
        p3=new ListEmps();
        p4=new ModifyEmp();
        p5=new CategoryPanel();
        p6=new Style();
        DynamicPanel .setLayout(layout);
        DynamicPanel.add(p1);
        DynamicPanel.add(p2);
        DynamicPanel.add(p3);
        DynamicPanel.add(p4);
        DynamicPanel.add(p5);
        DynamicPanel.add(p6);
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
       p5.setVisible(false);
       p6.setVisible(false);
        
        s=new sound();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelAdminBatch = new javax.swing.JLabel();
        jLabelAdmin = new javax.swing.JLabel();
        jPanelLogOut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabellogout = new javax.swing.JLabel();
        jPanelListAllEmps = new javax.swing.JPanel();
        jLabelListAllEmpsIcon = new javax.swing.JLabel();
        jLabelListAllEmpsWord = new javax.swing.JLabel();
        ModifyEmp = new javax.swing.JPanel();
        jLabelModifyEmp = new javax.swing.JLabel();
        jLabelmodifylEmp = new javax.swing.JLabel();
        AddNewEmp = new javax.swing.JPanel();
        jLabeladdEmpIcon = new javax.swing.JLabel();
        jLabelAddEmpWord = new javax.swing.JLabel();
        Category = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Styles = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        jPanel5.setBackground(new java.awt.Color(0, 136, 167));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setBackground(new java.awt.Color(0, 136, 167));
        setName("AdminFrame"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 136, 167));

        jLabelAdminBatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdminBatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Police_Badge_100px.png"))); // NOI18N

        jLabelAdmin.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdmin.setText("Admin");

        jPanelLogOut.setBackground(new java.awt.Color(0, 136, 167));
        jPanelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLogOutMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Exit_48px.png"))); // NOI18N

        jLabellogout.setBackground(new java.awt.Color(0, 136, 167));
        jLabellogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabellogout.setForeground(new java.awt.Color(240, 240, 240));
        jLabellogout.setText("Log out");

        javax.swing.GroupLayout jPanelLogOutLayout = new javax.swing.GroupLayout(jPanelLogOut);
        jPanelLogOut.setLayout(jPanelLogOutLayout);
        jPanelLogOutLayout.setHorizontalGroup(
            jPanelLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogOutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabellogout)
                    .addComponent(jLabel1))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelLogOutLayout.setVerticalGroup(
            jPanelLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogOutLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabellogout))
        );

        jPanelListAllEmps.setBackground(new java.awt.Color(0, 136, 167));
        jPanelListAllEmps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelListAllEmpsMousePressed(evt);
            }
        });

        jLabelListAllEmpsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListAllEmpsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/Report.png"))); // NOI18N

        jLabelListAllEmpsWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelListAllEmpsWord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelListAllEmpsWord.setText("  List ALL Employes");

        javax.swing.GroupLayout jPanelListAllEmpsLayout = new javax.swing.GroupLayout(jPanelListAllEmps);
        jPanelListAllEmps.setLayout(jPanelListAllEmpsLayout);
        jPanelListAllEmpsLayout.setHorizontalGroup(
            jPanelListAllEmpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListAllEmpsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelListAllEmpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListAllEmpsWord, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListAllEmpsLayout.createSequentialGroup()
                        .addComponent(jLabelListAllEmpsIcon)
                        .addContainerGap())))
        );
        jPanelListAllEmpsLayout.setVerticalGroup(
            jPanelListAllEmpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListAllEmpsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListAllEmpsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelListAllEmpsWord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ModifyEmp.setBackground(new java.awt.Color(0, 136, 167));
        ModifyEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModifyEmpMousePressed(evt);
            }
        });

        jLabelModifyEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModifyEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Change_User_96px.png"))); // NOI18N

        jLabelmodifylEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelmodifylEmp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmodifylEmp.setText("Modify Employees");

        javax.swing.GroupLayout ModifyEmpLayout = new javax.swing.GroupLayout(ModifyEmp);
        ModifyEmp.setLayout(ModifyEmpLayout);
        ModifyEmpLayout.setHorizontalGroup(
            ModifyEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModifyEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyEmpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelmodifylEmp))
                    .addComponent(jLabelModifyEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ModifyEmpLayout.setVerticalGroup(
            ModifyEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelModifyEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelmodifylEmp)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        AddNewEmp.setBackground(new java.awt.Color(0, 136, 167));
        AddNewEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddNewEmpMousePressed(evt);
            }
        });

        jLabeladdEmpIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeladdEmpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/Add_User.png"))); // NOI18N

        jLabelAddEmpWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddEmpWord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddEmpWord.setText("Add NEW Employee");

        javax.swing.GroupLayout AddNewEmpLayout = new javax.swing.GroupLayout(AddNewEmp);
        AddNewEmp.setLayout(AddNewEmpLayout);
        AddNewEmpLayout.setHorizontalGroup(
            AddNewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddNewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeladdEmpIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddEmpWord, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AddNewEmpLayout.setVerticalGroup(
            AddNewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeladdEmpIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAddEmpWord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Category.setBackground(new java.awt.Color(0, 136, 167));
        Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CategoryMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Checklist_100px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");

        javax.swing.GroupLayout CategoryLayout = new javax.swing.GroupLayout(Category);
        Category.setLayout(CategoryLayout);
        CategoryLayout.setHorizontalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );
        CategoryLayout.setVerticalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Styles.setBackground(new java.awt.Color(0, 136, 167));
        Styles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StylesMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Add_List_100px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Styles");

        javax.swing.GroupLayout StylesLayout = new javax.swing.GroupLayout(Styles);
        Styles.setLayout(StylesLayout);
        StylesLayout.setHorizontalGroup(
            StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StylesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StylesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(37, 37, 37))
        );
        StylesLayout.setVerticalGroup(
            StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StylesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdminBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdmin))
                .addGap(31, 31, 31)
                .addComponent(AddNewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanelListAllEmps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ModifyEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Styles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ModifyEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelListAllEmps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddNewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Styles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAdminBatch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))))
        );

        DynamicPanel.setBackground(new java.awt.Color(0, 136, 167));
        DynamicPanel.setToolTipText("");

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DynamicPanel.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewEmpMousePressed
        s.PlaySound();
        setColor(AddNewEmp);
        resetColor(jPanelListAllEmps);
        resetColor(Styles);
        resetColor(Category);
        resetColor(ModifyEmp);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
    }//GEN-LAST:event_AddNewEmpMousePressed

    private void jPanelListAllEmpsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelListAllEmpsMousePressed
        s.PlaySound();
        resetColor(AddNewEmp);
        setColor(jPanelListAllEmps);
        resetColor(Styles);
        resetColor(Category);
        resetColor(ModifyEmp);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p3.ResetTable();
    }//GEN-LAST:event_jPanelListAllEmpsMousePressed

    private void ModifyEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyEmpMousePressed
        s.PlaySound();
        resetColor(AddNewEmp);
        resetColor(jPanelListAllEmps);
        resetColor(Styles);
        resetColor(Category);
        setColor(ModifyEmp);
        p4.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        
    }//GEN-LAST:event_ModifyEmpMousePressed

    private void jPanelLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogOutMousePressed
         s.PlaySound();
         this.setVisible(false);
         L=new LogIn();
         L.setVisible(true);
         
    }//GEN-LAST:event_jPanelLogOutMousePressed

    private void StylesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StylesMousePressed
       s.PlaySound();
        setColor(Styles);
        resetColor(AddNewEmp);
        resetColor(jPanelListAllEmps);
        resetColor(Category);
        resetColor(ModifyEmp);
        p4.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(true);
    }//GEN-LAST:event_StylesMousePressed

    private void CategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMousePressed
       s.PlaySound();
        setColor(Category);
        resetColor(AddNewEmp);
        resetColor(jPanelListAllEmps);
        resetColor(Styles);
        resetColor(ModifyEmp);
        p4.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p5.setVisible(true);
        p6.setVisible(false);
        
    }//GEN-LAST:event_CategoryMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddNewEmp;
    private javax.swing.JPanel Category;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel ModifyEmp;
    private javax.swing.JPanel Styles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAddEmpWord;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelAdminBatch;
    private javax.swing.JLabel jLabelListAllEmpsIcon;
    private javax.swing.JLabel jLabelListAllEmpsWord;
    private javax.swing.JLabel jLabelModifyEmp;
    private javax.swing.JLabel jLabeladdEmpIcon;
    private javax.swing.JLabel jLabellogout;
    private javax.swing.JLabel jLabelmodifylEmp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelListAllEmps;
    private javax.swing.JPanel jPanelLogOut;
    // End of variables declaration//GEN-END:variables

 private void setColor(JPanel p) {
        p.setBackground(new java.awt.Color(0,153,204));
    }

    private void resetColor(JPanel p) {
        p.setBackground(new java.awt.Color(0,136,167));
    }






}
