/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import ControlClasses.Validation;
import DatabaseManager.DatabaseManager;
import java.awt.CardLayout;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author omar waheed
 */
public class LogIn extends javax.swing.JFrame {
CardLayout layout;
DatabaseManager D;
AdminFrame A;
EmployeeFrame E;
Validation v ;
    public LogIn() {
        initComponents();
        layout=new CardLayout();
     LogInAdmin.setVisible(false);
     ChoosePanel.setVisible(true);
     LogInEmp.setVisible(false);
     D=new DatabaseManager();
     v =new Validation();
     E=new EmployeeFrame();
     A=new AdminFrame();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoosePanel = new javax.swing.JPanel();
        jPanelEmp = new javax.swing.JPanel();
        Employee = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Admin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LogInAdmin = new javax.swing.JPanel();
        User = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelCancel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelAdminlogin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AdminEror = new javax.swing.JTextField();
        LogInEmp = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EmpCancel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EmpLogIn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        EmpEror = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setBackground(new java.awt.Color(0, 204, 204));

        ChoosePanel.setBackground(new java.awt.Color(0, 136, 167));

        jPanelEmp.setBackground(new java.awt.Color(0, 136, 167));
        jPanelEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelEmpMousePressed(evt);
            }
        });

        Employee.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        Employee.setForeground(new java.awt.Color(255, 255, 255));
        Employee.setText("Employee");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Management_96px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelEmpLayout = new javax.swing.GroupLayout(jPanelEmp);
        jPanelEmp.setLayout(jPanelEmpLayout);
        jPanelEmpLayout.setHorizontalGroup(
            jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpLayout.createSequentialGroup()
                .addGroup(jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Employee))
                    .addGroup(jPanelEmpLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelEmpLayout.setVerticalGroup(
            jPanelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Employee)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(34, 34, 34))
        );

        Admin.setBackground(new java.awt.Color(0, 136, 167));
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Police_Badge_100px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin");

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome");

        javax.swing.GroupLayout ChoosePanelLayout = new javax.swing.GroupLayout(ChoosePanel);
        ChoosePanel.setLayout(ChoosePanelLayout);
        ChoosePanelLayout.setHorizontalGroup(
            ChoosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChoosePanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jPanelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChoosePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(326, 326, 326))
        );
        ChoosePanelLayout.setVerticalGroup(
            ChoosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoosePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(ChoosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        LogInAdmin.setBackground(new java.awt.Color(0, 136, 167));
        LogInAdmin.setInheritsPopupMenu(true);

        User.setBackground(new java.awt.Color(0, 136, 167));
        User.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User.setForeground(new java.awt.Color(204, 204, 255));
        User.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        User.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserFocusGained(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Vrinda", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Vrinda", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password");

        jPanelCancel.setBackground(new java.awt.Color(0, 136, 167));
        jPanelCancel.setPreferredSize(new java.awt.Dimension(90, 102));
        jPanelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCancelMousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Cancel_48px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cancel");

        javax.swing.GroupLayout jPanelCancelLayout = new javax.swing.GroupLayout(jPanelCancel);
        jPanelCancel.setLayout(jPanelCancelLayout);
        jPanelCancelLayout.setHorizontalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelCancelLayout.setVerticalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10))
        );

        jPanelAdminlogin.setBackground(new java.awt.Color(0, 136, 167));
        jPanelAdminlogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelAdminloginFocusGained(evt);
            }
        });
        jPanelAdminlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAdminloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAdminloginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAdminloginMousePressed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Login_48px.png"))); // NOI18N
        jLabel8.setToolTipText("");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Log In");

        javax.swing.GroupLayout jPanelAdminloginLayout = new javax.swing.GroupLayout(jPanelAdminlogin);
        jPanelAdminlogin.setLayout(jPanelAdminloginLayout);
        jPanelAdminloginLayout.setHorizontalGroup(
            jPanelAdminloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminloginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAdminloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelAdminloginLayout.setVerticalGroup(
            jPanelAdminloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminloginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        Pass.setBackground(new java.awt.Color(0, 136, 167));
        Pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(204, 204, 255));
        Pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        Pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassFocusGained(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_School_Director_96px.png"))); // NOI18N

        jLabel20.setBackground(new java.awt.Color(0, 153, 204));
        jLabel20.setFont(new java.awt.Font("Sakkal Majalla", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Welcome Admin");

        AdminEror.setBackground(new java.awt.Color(0, 136, 167));
        AdminEror.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminEror.setForeground(new java.awt.Color(255, 255, 255));
        AdminEror.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdminEror.setBorder(null);

        javax.swing.GroupLayout LogInAdminLayout = new javax.swing.GroupLayout(LogInAdmin);
        LogInAdmin.setLayout(LogInAdminLayout);
        LogInAdminLayout.setHorizontalGroup(
            LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInAdminLayout.createSequentialGroup()
                .addGroup(LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInAdminLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel19))
                    .addGroup(LogInAdminLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInAdminLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6))
                    .addGroup(LogInAdminLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3))
                    .addGroup(LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(LogInAdminLayout.createSequentialGroup()
                            .addComponent(jPanelAdminlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(jPanelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Pass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(User, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AdminEror, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        LogInAdminLayout.setVerticalGroup(
            LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInAdminLayout.createSequentialGroup()
                .addGroup(LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInAdminLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LogInAdminLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LogInAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAdminlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(AdminEror, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        LogInEmp.setBackground(new java.awt.Color(0, 136, 167));
        LogInEmp.setInheritsPopupMenu(true);

        UserName.setBackground(new java.awt.Color(0, 136, 167));
        UserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(0, 204, 255));
        UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        UserName.setCaretColor(new java.awt.Color(255, 255, 255));
        UserName.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        UserName.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        UserName.setSelectionColor(new java.awt.Color(0, 255, 204));
        UserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserNameFocusGained(evt);
            }
        });

        Password.setBackground(new java.awt.Color(0, 136, 167));
        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 204, 255));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        Password.setCaretColor(new java.awt.Color(255, 255, 255));
        Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Password.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Password.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        Password.setSelectionColor(new java.awt.Color(0, 255, 204));
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Vrinda", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Username");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Vrinda", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Password");

        EmpCancel.setBackground(new java.awt.Color(0, 136, 167));
        EmpCancel.setPreferredSize(new java.awt.Dimension(90, 102));
        EmpCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmpCancelMousePressed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Cancel_48px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cancel");

        javax.swing.GroupLayout EmpCancelLayout = new javax.swing.GroupLayout(EmpCancel);
        EmpCancel.setLayout(EmpCancelLayout);
        EmpCancelLayout.setHorizontalGroup(
            EmpCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpCancelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(EmpCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        EmpCancelLayout.setVerticalGroup(
            EmpCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpCancelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14))
        );

        EmpLogIn.setBackground(new java.awt.Color(0, 136, 167));
        EmpLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpLogInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpLogInMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmpLogInMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Log In");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Login_48px.png"))); // NOI18N
        jLabel15.setToolTipText("");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout EmpLogInLayout = new javax.swing.GroupLayout(EmpLogIn);
        EmpLogIn.setLayout(EmpLogInLayout);
        EmpLogInLayout.setHorizontalGroup(
            EmpLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpLogInLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(EmpLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        EmpLogInLayout.setVerticalGroup(
            EmpLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpLogInLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Collaborator_Male_96px.png"))); // NOI18N

        jLabel18.setBackground(new java.awt.Color(0, 153, 204));
        jLabel18.setFont(new java.awt.Font("Sakkal Majalla", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Welcome Employee");

        EmpEror.setEditable(false);
        EmpEror.setBackground(new java.awt.Color(0, 136, 167));
        EmpEror.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpEror.setForeground(new java.awt.Color(255, 255, 255));
        EmpEror.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmpEror.setBorder(null);
        EmpEror.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout LogInEmpLayout = new javax.swing.GroupLayout(LogInEmp);
        LogInEmp.setLayout(LogInEmpLayout);
        LogInEmpLayout.setHorizontalGroup(
            LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInEmpLayout.createSequentialGroup()
                .addGroup(LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInEmpLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel18))
                    .addGroup(LogInEmpLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel17)))
                .addGap(105, 105, 105)
                .addGroup(LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInEmpLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel12))
                    .addGroup(LogInEmpLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11))
                    .addGroup(LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(LogInEmpLayout.createSequentialGroup()
                            .addComponent(EmpLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(EmpCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInEmpLayout.createSequentialGroup()
                .addComponent(EmpEror)
                .addGap(218, 218, 218))
        );
        LogInEmpLayout.setVerticalGroup(
            LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInEmpLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInEmpLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18))
                .addGap(21, 21, 21)
                .addGroup(LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInEmpLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(LogInEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmpLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(EmpEror, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChoosePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LogInAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LogInEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChoosePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LogInAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LogInEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMousePressed
     ChoosePanel.setVisible(false);
     LogInAdmin.setVisible(true);
     AdminReset();
    }//GEN-LAST:event_AdminMousePressed

    private void jPanelEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmpMousePressed
      ChoosePanel.setVisible(false);
      LogInEmp.setVisible(true);
      EmpReset();
    }//GEN-LAST:event_jPanelEmpMousePressed

    private void jPanelCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCancelMouseEntered
        setColor(jPanelCancel);
    }//GEN-LAST:event_jPanelCancelMouseEntered

    private void jPanelCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCancelMouseExited
        resetColor(jPanelCancel);
    }//GEN-LAST:event_jPanelCancelMouseExited

    private void jPanelAdminloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAdminloginMouseEntered
        setColor(jPanelAdminlogin);
    }//GEN-LAST:event_jPanelAdminloginMouseEntered

    private void jPanelAdminloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAdminloginMouseExited
         resetColor(jPanelAdminlogin);
    }//GEN-LAST:event_jPanelAdminloginMouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        setColor(jPanelAdminlogin);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jPanelEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmpMouseEntered
        setColor(jPanelEmp);
    }//GEN-LAST:event_jPanelEmpMouseEntered

    private void jPanelEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmpMouseExited
         resetColor(jPanelEmp);
    }//GEN-LAST:event_jPanelEmpMouseExited

    private void AdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseEntered
        setColor(Admin);
    }//GEN-LAST:event_AdminMouseEntered

    private void AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseExited
        resetColor(Admin);
    }//GEN-LAST:event_AdminMouseExited

    private void EmpCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpCancelMouseEntered
        setColor(EmpCancel);
    }//GEN-LAST:event_EmpCancelMouseEntered

    private void EmpCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpCancelMouseExited
        resetColor(EmpCancel);
    }//GEN-LAST:event_EmpCancelMouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        setColor(EmpLogIn);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void EmpLogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpLogInMouseEntered
        setColor(EmpLogIn);
    }//GEN-LAST:event_EmpLogInMouseEntered

    private void EmpLogInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpLogInMouseExited
        resetColor(EmpLogIn);
    }//GEN-LAST:event_EmpLogInMouseExited

    private void jPanelCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCancelMousePressed
       LogInAdmin.setVisible(false);
       ChoosePanel.setVisible(true);
    }//GEN-LAST:event_jPanelCancelMousePressed

    private void EmpCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpCancelMousePressed
       LogInEmp.setVisible(false);
       ChoosePanel.setVisible(true);
    }//GEN-LAST:event_EmpCancelMousePressed

    private void EmpLogInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpLogInMousePressed
          EmpLogIn.requestFocusInWindow();
        if (!v.IsEmpty(UserName.getText())&&!v.IsEmpty(Password.getText())&&v.IsNumber(Password.getText())&&v.IsUserName(UserName.getText())&&D.SearchLogInData(UserName.getText(),Integer.parseInt(Password.getText()),"Employees")) {
            this.setVisible(false);
            E.setVisible(true);
             }
        else{           
            EmpEror.setText("Invalid User Name Or Password");
         
             }
        
        EmpReset();
    }//GEN-LAST:event_EmpLogInMousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
           Admin.requestFocusInWindow();
          if (!v.IsEmpty(User.getText())&&!v.IsEmpty(Pass.getText())&&v.IsNumber(Pass.getText())&&v.IsUserName(User.getText())&&D.SearchLogInData(User.getText(),Integer.parseInt(Pass.getText()),"Admin")) {
            this.setVisible(false);
            A.setVisible(true);
        }else
          {
            AdminEror.setText("Invalid User Name Or Password");
          } 
    
        AdminReset();
    }//GEN-LAST:event_jLabel15MousePressed

    private void jPanelAdminloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAdminloginMousePressed
          jPanelAdminlogin.requestFocusInWindow();
         

          if (!v.IsEmpty(User.getText())&&!v.IsEmpty(Pass.getText())&&v.IsNumber(Pass.getText())&&v.IsUserName(User.getText())&&D.SearchLogInData(User.getText(),Integer.parseInt(Pass.getText()),"Admin")) {
            this.setVisible(false);
            A.setVisible(true);
        }else
          {
            AdminEror.setText("Invalid User Name Or Password");
          }
    
        AdminReset();
    }//GEN-LAST:event_jPanelAdminloginMousePressed

    private void UserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNameFocusGained
     EmpEror.setText("");
    }//GEN-LAST:event_UserNameFocusGained

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
      EmpEror.setText("");
    }//GEN-LAST:event_PasswordFocusGained

    private void UserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserFocusGained
      AdminEror.setText("");
    }//GEN-LAST:event_UserFocusGained

    private void PassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassFocusGained
       AdminEror.setText("");
    }//GEN-LAST:event_PassFocusGained

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
              
          if (!v.IsEmpty(User.getText())&&!v.IsEmpty(Pass.getText())&&v.IsNumber(Pass.getText())&&v.IsUserName(User.getText())&&D.SearchLogInData(User.getText(),Integer.parseInt(Pass.getText()),"Admin")) {
            this.setVisible(false);
            A.setVisible(true);
        }else
          {
            AdminEror.setText("Invalid User Name Or Password");
          } 
    
        AdminReset();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jPanelAdminloginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelAdminloginFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAdminloginFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JTextField AdminEror;
    private javax.swing.JPanel ChoosePanel;
    private javax.swing.JPanel EmpCancel;
    private javax.swing.JTextField EmpEror;
    private javax.swing.JPanel EmpLogIn;
    private javax.swing.JLabel Employee;
    private javax.swing.JPanel LogInAdmin;
    private javax.swing.JPanel LogInEmp;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField User;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAdminlogin;
    private javax.swing.JPanel jPanelCancel;
    private javax.swing.JPanel jPanelEmp;
    // End of variables declaration//GEN-END:variables

    private void setColor(JPanel p) {
        p.setBackground(new java.awt.Color(0,153,204));
    }

    private void resetColor(JPanel p) {
        p.setBackground(new java.awt.Color(0,136,167));
    }
    void  AdminReset(){
    User.setText("");
    Pass.setText("");
    }
    void EmpReset(){
    UserName.setText("");
    Password.setText("");
    }
}

