/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.EmployeePanels;

import ControlClasses.Apparel;
import DatabaseManager.DatabaseManager;

/**
 *
 * @author omar waheed
 */
public class ModifyApparel extends javax.swing.JPanel {
  DatabaseManager D;
  Apparel A=new Apparel();
    
    public ModifyApparel() {
        initComponents();
        D=new DatabaseManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Appareel = new javax.swing.JPanel();
        TypeTextField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        QuantityTextField = new javax.swing.JTextField();
        CategoryTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ApparelEror = new javax.swing.JTextField();
        StyleTextField = new javax.swing.JTextField();
        UpdateApparel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SearchApparelTextField = new javax.swing.JTextField();
        SearchApparel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        Appareel.setBackground(new java.awt.Color(255, 255, 255));
        Appareel.setPreferredSize(new java.awt.Dimension(1014, 463));

        TypeTextField.setBackground(new java.awt.Color(0, 102, 255));
        TypeTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TypeTextField.setForeground(new java.awt.Color(255, 255, 255));
        TypeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TypeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        TypeTextField.setCaretColor(new java.awt.Color(51, 255, 255));
        TypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTextFieldActionPerformed(evt);
            }
        });

        PriceTextField.setBackground(new java.awt.Color(0, 102, 255));
        PriceTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PriceTextField.setForeground(new java.awt.Color(255, 255, 255));
        PriceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PriceTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        PriceTextField.setCaretColor(new java.awt.Color(51, 255, 255));
        PriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTextFieldActionPerformed(evt);
            }
        });

        QuantityTextField.setBackground(new java.awt.Color(0, 102, 255));
        QuantityTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QuantityTextField.setForeground(new java.awt.Color(255, 255, 255));
        QuantityTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantityTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        QuantityTextField.setCaretColor(new java.awt.Color(51, 255, 255));
        QuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTextFieldActionPerformed(evt);
            }
        });

        CategoryTextField.setBackground(new java.awt.Color(0, 102, 255));
        CategoryTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CategoryTextField.setForeground(new java.awt.Color(255, 255, 255));
        CategoryTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CategoryTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        CategoryTextField.setCaretColor(new java.awt.Color(51, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Type");

        jLabel2.setBackground(new java.awt.Color(0, 153, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Price");

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Quantity");

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Category");

        jLabel5.setBackground(new java.awt.Color(0, 153, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Style");

        ApparelEror.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ApparelEror.setForeground(new java.awt.Color(0, 153, 204));
        ApparelEror.setBorder(null);

        StyleTextField.setBackground(new java.awt.Color(0, 102, 255));
        StyleTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StyleTextField.setForeground(new java.awt.Color(255, 255, 255));
        StyleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StyleTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        StyleTextField.setCaretColor(new java.awt.Color(51, 255, 255));
        StyleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StyleTextFieldActionPerformed(evt);
            }
        });

        UpdateApparel.setBackground(new java.awt.Color(255, 255, 255));
        UpdateApparel.setPreferredSize(new java.awt.Dimension(144, 144));
        UpdateApparel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateApparelMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateApparelMousePressed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Available_Updates_80px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UpdateApparel");

        javax.swing.GroupLayout UpdateApparelLayout = new javax.swing.GroupLayout(UpdateApparel);
        UpdateApparel.setLayout(UpdateApparelLayout);
        UpdateApparelLayout.setHorizontalGroup(
            UpdateApparelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateApparelLayout.setVerticalGroup(
            UpdateApparelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateApparelLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(15, 15, 15))
        );

        SearchApparelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchApparelTextFieldActionPerformed(evt);
            }
        });

        SearchApparel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchApparelMousePressed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icons8_Search_Property_96px.png"))); // NOI18N

        javax.swing.GroupLayout SearchApparelLayout = new javax.swing.GroupLayout(SearchApparel);
        SearchApparel.setLayout(SearchApparelLayout);
        SearchApparelLayout.setHorizontalGroup(
            SearchApparelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        SearchApparelLayout.setVerticalGroup(
            SearchApparelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AppareelLayout = new javax.swing.GroupLayout(Appareel);
        Appareel.setLayout(AppareelLayout);
        AppareelLayout.setHorizontalGroup(
            AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppareelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(102, 102, 102)
                .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppareelLayout.createSequentialGroup()
                        .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TypeTextField)
                            .addComponent(PriceTextField)
                            .addComponent(QuantityTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CategoryTextField)
                            .addComponent(StyleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addGap(120, 120, 120)
                        .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchApparelTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(UpdateApparel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(SearchApparel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ApparelEror, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        AppareelLayout.setVerticalGroup(
            AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppareelLayout.createSequentialGroup()
                .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppareelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(SearchApparelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(AppareelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(SearchApparel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AppareelLayout.createSequentialGroup()
                        .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(AppareelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StyleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(UpdateApparel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(ApparelEror, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Appareel, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Appareel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeTextFieldActionPerformed

    private void PriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTextFieldActionPerformed

    private void QuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTextFieldActionPerformed

    private void StyleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StyleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StyleTextFieldActionPerformed

    private void UpdateApparelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateApparelMouseEntered

    }//GEN-LAST:event_UpdateApparelMouseEntered

    private void UpdateApparelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateApparelMousePressed
         D.UpdateStringData("Apparel","Type",SearchApparelTextField.getText(),TypeTextField.getText(),"StockId");
         D.UpdateintData("Apparel","Quantity",SearchApparelTextField.getText(),Integer.parseInt(QuantityTextField.getText()),"StockId");
         D.UpdateFloatData("Apparel","PricePerItem",SearchApparelTextField.getText(),Float.parseFloat(PriceTextField.getText()),"StockId");
         D.UpdateStringData("Apparel","Category",SearchApparelTextField.getText(),CategoryTextField.getText(),"StockId");
         D.UpdateStringData("Apparel", "Style",SearchApparelTextField.getText(),StyleTextField.getText(),"StockId");
         System.out.println("Data Updated Successfully");
    }//GEN-LAST:event_UpdateApparelMousePressed

    private void SearchApparelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchApparelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchApparelTextFieldActionPerformed

    private void SearchApparelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchApparelMousePressed
     if(  D.SearchApparelData(Integer.parseInt(SearchApparelTextField.getText()) ))
     {      ApparelEror.setText("Apparel Found");
            A=D.UpDateApparelData(Integer.parseInt(SearchApparelTextField.getText()));
            TypeTextField.setText(A.getType());
            PriceTextField.setText(""+A.getPricePerItem());
            QuantityTextField.setText(""+A.getQuantity());
            CategoryTextField.setText(A.GetCategory());
            StyleTextField.setText(A.GetStyle());
             ApparelEror.setText("Apparel Was Updated Successfully");
     }
     else
     {
         ApparelEror.setText("ApparelNotFound");
     }
    }//GEN-LAST:event_SearchApparelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appareel;
    private javax.swing.JTextField ApparelEror;
    private javax.swing.JTextField CategoryTextField;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JTextField QuantityTextField;
    private javax.swing.JPanel SearchApparel;
    private javax.swing.JTextField SearchApparelTextField;
    private javax.swing.JTextField StyleTextField;
    private javax.swing.JTextField TypeTextField;
    private javax.swing.JPanel UpdateApparel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
